{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "canvas.serviceAccountName" . }}
  labels:
{{ include "canvas.labels" . | indent 4 }}
{{- end }}
